### ISSUE TITLE
Sprites render as fully purple/pink squares and shapes.

### ISSUE THREAD

**Issue by Morenofael** [PaleCourt/PaleCourt#22]
Operational System: Ubuntu 22.04.
Hollow Knight version: 1.5 or above.
Downloaded using Scarab

**Comment by CausticWarrior** [comment]
I have the same problem on Mac 13.4.1

**Comment by Dr-Turtle** [comment]
I also have this issue on Arch Linux

**Comment by CausticWarrior** [comment]
I took a screen recording of it for the bug fix. Is this what you're seeing?

https://github.com/PaleCourt/PaleCourt/assets/110358212/f99affe9-795a-44ad-ace5-9a716254ab7d

**Comment by Morenofael** [comment]
> I took a screen recording of it for the bug fix. Is this what you're seeing?
> 250392328-da16e710-ce63-4e46-9856-73c8dd5097a5.mov

That's exactly the problem I'm having. In-game sprites also have this color, except Drya for some reason.

**Comment by CausticWarrior** [comment]
Having same problem as cionx.

**Comment by huantianad** [comment]
This also occurs on NixOS, seems to be a Linux specific issue?

**Comment by Morenofael** [comment]
> This also occurs on NixOS, seems to be a Linux specific issue?

Systems based on Unix, since MacOS users had the same issues.

**Comment by FFFluoride** [comment]
I am having the same issue on pop os

**Comment by alexander-schoch-linuxdays** [comment]
Workaround: In order to remove the pink squares, use the windows version of Hollow Knight through proton. How to: https://www.youtube.com/watch?v=8wnvqLFZD1c

Depending on your hardware, you might need to enable wined3d by setting `PROTON_USE_WINED3D=1 %command%` in the launch options.
