### ISSUE TITLE
Error Pale Court

### ISSUE THREAD

**Issue by lunaewill** [PaleCourt/PaleCourt#26]
I can't download this mod, every time I try, I get a message saying that scarab was unable to access the Hollow Knight mods folder.
Please help me, I really want to play #

**Comment by HyScript7** [comment]
This isn't necessarily an issue with Pale Court.
Make sure you have access to read and write into the mods folder in your hollow knight installation. Right clicking the folder and changing ownership to your account with all permissions should resolve the issue.
If the issue persists, try deleting the mods folder, patching the hollow knight installation from steam and then try installing the mod again. This should create the mods folder again with the proper permissions.
If you're on linux / mac, run `chmod 770` on the mods folder.

**Comment by Clazex** [comment]
Closing as this is more related to the mod installer rather than this mod.
