### ISSUE TITLE
Dream nailing Dryya doesn't work

### ISSUE THREAD

**Issue by TheIllusionist0** [PaleCourt/PaleCourt#28]
Dream nailing the other knights works perfectly fine, but dream nailing Dryya loads me into the dream world for a moment before kicking me back into Queen's Gardens as soon as the Knight's entrance animation finishes. Tried reloading game, no luck.

Completed save file; 112, saved Zote, gave flowers to everybody. Not really sure if there's anything I did to cause this.

Let me know if any files would help, I'd love nothing more than to contribute to this mod being as amazing as it can be, however I can. Everything else is incredible so far.

**Comment by TheRealFollow** [comment]
Same issue is occurring to me. New save file with not all items obtained, nor have I beaten the game yet on this save.
Area loads up for a few frames, loads in the knight, and the immediately transitions to outside Dryya with the Knight lying down and able to move around at first.

**Comment by TheIllusionist0** [comment]
Checked the Discord and found out it's a mod conflict with Additional Maps. Closing issue; hoping this gets fixed, but understandable if it's not high on the devs' priority list.

**Comment by Connr06** [comment]
I wanted to mention that the mod "The Glimmering Realm" shares a similar if not the same issue.
