### ISSUE TITLE
Invisible Hegemol 

### ISSUE THREAD

**Issue by Firebroke** [PaleCourt/PaleCourt#31]
Hegemol boss fight initiates, boss can still attack but boss and all attack animations are invisible.

Checked mods installed, and turned off others that may conflict, reduced mod pack to pale court only, issue persists. All other boss interactions remain normal.

**Comment by TheShaspio** [comment]
Latest update seems to be the cause!

https://drive.google.com/file/d/11JENScxwc0t70TXgwVEfS4IxQ3r3M9XU/view

**Comment by Firebroke** [comment]
just updated the mod pack again, problem seems to be solved, Hegemol fight seems to be working as intended.

To clarify my previous post the boss simply wouldn't appear but could still deal damage.
