### ISSUE TITLE
Pale Court

### ISSUE THREAD

**Issue by lorepro06** [PaleCourt/PaleCourt#32]
ogni volta che provo a entrare con l'aculeo dei sogni nella mente della dama bianca per combatterla, mi carica la mappa, compare il mio personaggio per poi ricaricare tutto buttandomi fuori dalla mente della dama bianca, COME POSSO FARE?

**Comment by Clazex** [comment]
I assume you mean Dryya, please uninstall `Additional Maps` mod for now as it is currently conflicting with her fight.
