### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by AmirMohG** [PaleCourt/PaleCourt#37]
Thanks for the great mod, been enjoying watching the playthroughs on YT. I'm using Scarab but the game gets stuck on the loading screen (I also have the dependency mods). I'm able to send more info if the issue isn't known yet.

**Comment by liushengqi000** [comment]
set  the launch parameters to -force-opengl ?

**Comment by Ordoviz** [comment]
Are any errors written to `~/.config/unity3d/Team\ Cherry/Hollow\ Knight/ModLog.txt`?

**Comment by AmirMohG** [comment]
> -force-opengl

this seemed to fix it, thanks
