### ISSUE TITLE
Mod does not load, is there any way this can be resolved?

### ISSUE THREAD

**Issue by AlexPhantom24** [PaleCourt/PaleCourt#40]
Sorry for any inconveniences but I have been trying to play the Pale Court mod for Hollow Knight and it simply just does not run. Every time I run the game, the loading mod bar shows up but it always crashes with the following screen:
![IMG_9821](https://github.com/PaleCourt/PaleCourt/assets/138908914/a79b49f9-406b-46a3-97b9-e476b604ae26)
I do not know what to do anymore so please help!

**Comment by liushengqi000** [comment]
set the launch parameters to -force-opengl ? GPU might have no Vulkan support.

**Comment by AlexPhantom24** [comment]
> set the launch parameters to -force-opengl ? GPU might have no Vulkan support.

How do I do that?

**Comment by AlexPhantom24** [comment]
I have resolved the issue by updating my GPU statistics, thank you for helping!
