### ISSUE TITLE
Dryaa's dream instant kick

### ISSUE THREAD

**Issue by Mini-Toad** [PaleCourt/PaleCourt#42]
Hello,

When I try to get into Dryaa's dream, the teleportation animation plays, I can see for a split seconds the dream and the knight in it, but it then instantly kicks me out as if I died in the dream, without further animation. Once back, the knight waking up animation starts but it can moves normally even before the animation ends. https://imgur.com/a/dfcLXP8 for the video

**Comment by Acu1000** [comment]
This is a known issue, make sure to disable the following mods:
-AdditionalMaps
-Extra MenuBackgrounds
-EssenceAlways 
That should fix it
