### ISSUE TITLE
Problems with object display

### ISSUE THREAD

**Issue by paul0728** [PaleCourt/PaleCourt#49]
Hello, I'm running the game in ubuntu, and I've downloaded the pale court mod and dependencies, but the object display seems to have a problem, how can I fix it, thank you!

![Screenshot from 2023-08-12 00-57-15](https://github.com/PaleCourt/PaleCourt/assets/44644609/e8029a36-3b6b-421c-b0a7-40a970143f09)

ModLog.txt:
﻿[INFO]:[API] - Starting mod loading
[INFO]:[API] - Loading Global Settings
[INFO]:[API] - Deleting modlogs older than 7 days ago
[INFO]:[FrogCore] - Initializing
[INFO]:[FiveKnights] - Initializing
[INFO]:[FiveKnights] - Loading Global Settings
[INFO]:[Language] Loaded Language
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.WHegemol_full_2.png
[INFO]:[FiveKnights] - Created sprite from embedded image: WHegemol_full_2 at ind 1
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.black.png
[INFO]:[FiveKnights] - Created sprite from embedded image: black at ind 2
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Isma.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Isma at ind 3
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Dryya.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Dryya at ind 4
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Zemer.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Zemer at ind 5
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Hegemol.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Hegemol at ind 6
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Dryya_Silver.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Dryya_Silver at ind 7
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Isma_Silver.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Isma_Silver at ind 8
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Zemer_Silver.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Zemer_Silver at ind 9
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Hegemol_Silver.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Hegemol_Silver at ind 10
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.mace.png
[INFO]:[FiveKnights] - Created sprite from embedded image: mace at ind 11
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.ach_dryya.png
[INFO]:[FiveKnights] - Created sprite from embedded image: ach_dryya at ind 12
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.ach_heg.png
[INFO]:[FiveKnights] - Created sprite from embedded image: ach_heg at ind 13
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.ach_isma.png
[INFO]:[FiveKnights] - Created sprite from embedded image: ach_isma at ind 14
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.ach_zem.png
[INFO]:[FiveKnights] - Created sprite from embedded image: ach_zem at ind 15
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.ach_panth.png
[INFO]:[FiveKnights] - Created sprite from embedded image: ach_panth at ind 16
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.DlcList.png
[INFO]:[FiveKnights] - Created sprite from embedded image: DlcList at ind 17
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.LogoBlack.png
[INFO]:[FiveKnights] - Created sprite from embedded image: LogoBlack at ind 18
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Petal.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Petal at ind 19
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Abyssal_Bloom.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Abyssal_Bloom at ind 20
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Boon_of_Hallownest.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Boon_of_Hallownest at ind 21
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Dagger.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Dagger at ind 22
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Defenders_Crest.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Defenders_Crest at ind 23
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_icon_dryya.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_icon_dryya at ind 24
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_icon_hegemol.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_icon_hegemol at ind 25
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_icon_isma.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_icon_isma at ind 26
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_icon_zemer.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_icon_zemer at ind 27
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_icon_tiso.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_icon_tiso at ind 28
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_dryya.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_dryya at ind 29
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_hegemol.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_hegemol at ind 30
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_isma.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_isma at ind 31
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_zemer.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_zemer at ind 32
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.journal_tiso.png
[INFO]:[FiveKnights] - Created sprite from embedded image: journal_tiso at ind 33
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Kings_Honour.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Kings_Honour at ind 34
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Mark_of_Purity.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Mark_of_Purity at ind 35
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Vessels_Lament.png
[INFO]:[FiveKnights] - Created sprite from embedded image: Vessels_Lament at ind 36
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.acid_a.png
[INFO]:[FiveKnights] - Created sprite from embedded image: acid_a at ind 37
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.acid_b.png
[INFO]:[FiveKnights] - Created sprite from embedded image: acid_b at ind 38
[INFO]:[FiveKnights] - looking at file FiveKnights.assets.Language.json
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.abyssaltemple
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.artistsbund
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.blendvertexcolor
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.charmunlock
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.creditsbundle
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.dependencies overworld
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.dryyawin
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ggarenadep
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ggarenadryya
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ggarenahegemol
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ggarenahub
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ggarenaisma
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ggarenazemer
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.hegemolwin
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.hubasset1
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ismabg
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.ismawin
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.miscbund
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.owarenadep
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.owarenadryya
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.owarenahegemol
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.owarenaisma
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.owarenazemer
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.pureamulets
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.radiantroom
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.rewardroom
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.soundbund
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.tisobundle
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.titlescreen
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.workshopdep
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.workshopentrance
[INFO]:[FiveKnights] - looking at file FiveKnights.StreamingAssets.zemerwin
[INFO]:[Language] Loaded Language
[INFO]:[Language] Loaded Language
[INFO]:[API] - Preloaded reflection in 1755ms
[INFO]:[FiveKnights] - Finished bundling
[INFO]:[SFCoreMod] - Initializing
[INFO]:[SFCoreMod] - Loading Global Settings
[INFO]:[API] - Assembly WavLib (1.0.1.0) loaded with 0 mods
[INFO]:[API] - Assembly Vasi (2.0.0.0) loaded with 0 mods
[INFO]:[API] - Creating mod preloads
[INFO]:[FiveKnights] - Start
[INFO]:[FiveKnights] - Storing GOs
[INFO]:[FiveKnights] - Initializing
[INFO]:[API] - Finished loading mods:
[INFO]:[API] - Modding API: 1.5.78.11833-74
[INFO]:[API] - FrogCore : 2.0.0.1
[INFO]:[API] - Pale Court : 1.0.1.0
[INFO]:[API] - SFCore : 1.5.9.0-db80f3
[INFO]:[API] - 
[INFO]:[FiveKnights] - Saving Global Settings
[INFO]:[SFCoreMod] - Saving Global Settings
[INFO]:[API] - Saving Global Settings

**Comment by SalehAce1** [comment]
Are you using proton/wine? You should be running the game natively.

**Comment by LGCW** [comment]
The latest version of the MOD fixes the graphical corruption on Linux. You no longer have to use Proton as a workaround.

**Comment by paul0728** [comment]
@SalehAce1 @LGCW 
Hello, I have a new problem, I found that after running the game with proton, and then without proton, the game will be updated first, and the native game can be run. But if you close steam and open it again, the game will be updated automatically, and you can't run the game in native mode. So how to solve this problem? Or is it possible to solve the screen display problem by using proton? I tried to set the startup parameter "-force-opengl", but I get "InitializeEngineGraphics failed" error.
Thank you for your help.
