### ISSUE TITLE
Cannot figt Isma nor Ze'mer

### ISSUE THREAD

**Issue by Neathle** [PaleCourt/PaleCourt#56]
I have tried both these fight so far and both failed to load. Isma's arena loads but she never appears, the door closes after you enter the room but nothing happens after. With Ze'mer, the screen goes white but nothing happens.

Mods installed:
- Core.FsmUtil
- FrogCore
- Hallownest-Vocalized
- Hallownest-Vocalized-AudioLoader
- HKMirror
- Osmi
- Pale Court
- SFCore
- Vasi

**Comment by Neathle** [comment]
Found that Pale Court is not compatible with Vocalized at the moment

**Comment by SFGrenade** [comment]
gonna close this then
