### ISSUE TITLE
Hollownest vocalized and pale court bug

### ISSUE THREAD

**Issue by ComedyOutput** [PaleCourt/PaleCourt#57]
when both hollownest vocalyzed and pale court are enabled, if you enter a pale court boss arena (at least hegemol, i haven't tested others) the screen turns completely white. i've had to reload the game to get rid of it but it repeats, if attempted again, while HV is enabled.

**Comment by Dawoodywoody** [comment]
same man

**Comment by SFGrenade** [comment]
identical to https://github.com/PaleCourt/PaleCourt/issues/56#issuecomment-1773790126
