### ISSUE TITLE
Wondering if it is possible to use mod without killing dreamers.

### ISSUE THREAD

**Issue by GrimReaper99999** [PaleCourt/PaleCourt#58]
I am playing with the pale court mod installed, and am attempting to do a playthrough without killing the dreamers. however, after looking it up, you must defeat the White Defender dream boss. as such, I am wondering if it is possible to add an option where you can fight the White Defender without killing the dreamers. Thank you!

**Comment by SalehAce1** [comment]
Hi
The mod is meant to fall in line with the game so we won't be changing this, sorry. Feel free to simply fight the bosses in godseeker mode. Also, I'm not sure what you mean by doing a playthrough without killing the dreamers since you have to kill them to beat the game.

**Comment by GrimReaper99999** [comment]
You can beat the game without killing the dreamers by doing the Godhome ending, which, while requiring you to beat Uumuu and the watcher knights, does not require you to actually unseal the black egg, or at least according to the wiki. I have only gotten to pantheon 3 as of now.
