### ISSUE TITLE
Dryya boss bug.

### ISSUE THREAD

**Issue by 31kJack** [PaleCourt/PaleCourt#62]
When i teleport into Dryya's areana it instantly teleports me back, not even being able to move while im there. i suspect because it think i lost? this has not happened with isma's, or helemolg one so im not sure

**Comment by JoshDa777** [comment]
I can only think that it could be a bug in the animations so I suggest trying it without the mods that change the animations like Qol's

**Comment by SFGrenade** [comment]
> I can only think that it could be a bug in the animations so I suggest trying it without the mods that change the animations like Qol's

nope, this is because pale court has some scene loading weirdness and mods like additional maps cause pale court to not load the floor in time and you get booted out of the arenas, so @31kJack try uninstalling mods like AdditionalMaps for the time being.
